version: '3.3'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=internship
    ports:
      - "3306:3306"
    restart: always


  internshipservice:
    image: internship
    container_name: internship-app
    ports:
      - "8085:8085"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./upload:/data/upload"
    restart: always
    depends_on:
      - "db"

volumes:
  upload: